classifier__C: 0.1
classifier__max_iter: 1000
classifier__penalty: l1
classifier__solver: liblinear
scaler: null
selectkbest__k: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AQAAAA==
